<?php

namespace Goldnead\ClientRooms\Tests\Feature;

use Goldnead\ClientRooms\Facades\ClientRooms;
use Goldnead\ClientRooms\Models\ClientRoomSession;
use Goldnead\ClientRooms\Tests\TestCase;
use PHPUnit\Framework\Attributes\Test;
use Statamic\Facades\Antlers;

/**
 * The write-up: the one value in a room that is markup, and the readers that
 * each need it differently.
 *
 * A session's protocol is HTML, generated by whatever system ran the sitting.
 * That makes it the only field here where "escape everything" and "show the
 * client something readable" pull against each other, and where getting it
 * wrong is quiet: escaped whole, the client reads `<h3>` in words; printed
 * raw, a page renders markup nobody in this addon wrote.
 *
 * The tests that matter most are the two that fail silently:
 *
 * - A bare `<` in the text. `strip_tags` reads `3<5 Minuten` as the start of a
 *   tag and eats the rest of the protocol. Nothing throws, nothing logs, the
 *   client simply gets half a write-up.
 * - `has_protocol` on a protocol that holds tags and no words.
 */
class SessionProtocolTest extends TestCase
{
    /** The third argument marks the template as trusted; without it Antlers runs no tags. */
    protected function parse(string $template): string
    {
        return (string) Antlers::parse($template, [], true);
    }

    protected function actAsClient(string $email = 'maria@example.com'): void
    {
        $user = $this->userWithPermission();
        $user->email($email)->save();

        $this->actingAs($user);
    }

    protected function withProtocol(string $protocol): ClientRoomSession
    {
        return ClientRooms::importSession($this->room(), 'vf-0001', [
            'title' => 'Sitzung',
            'published_status' => ClientRoomSession::PUBLISHED_PUBLISHED,
            'protocol' => $protocol,
        ]);
    }

    // ── The bare `<` ────────────────────────────────────────────────────────

    #[Test]
    public function a_bare_less_than_sign_does_not_swallow_the_rest_of_the_write_up(): void
    {
        // The write-up is generated elsewhere and nothing obliges that system
        // to encode its own text. `strip_tags` alone reads "3<5" as an opening
        // tag and drops everything to the next `>` — here, to the end.
        $session = $this->withProtocol('<p>Wir haben 3<5 Minuten geübt und danach noch mehr.</p>');

        $text = $session->protocolText();

        $this->assertStringContainsString('Wir haben 3', $text);
        $this->assertStringContainsString('danach noch mehr.', $text);
        $this->assertStringNotContainsString('<p>', $text);
    }

    #[Test]
    public function a_bare_less_than_sign_survives_all_the_way_to_the_client(): void
    {
        $this->withProtocol('<p>Wir haben 3<5 Minuten geübt und danach noch mehr.</p>');

        $this->actAsClient();

        $output = $this->parse('{{ client_room }}{{ sessions }}{{ protocol }}{{ /sessions }}{{ /client_room }}');

        $this->assertStringContainsString('danach noch mehr.', $output);
    }

    #[Test]
    public function real_tags_are_still_stripped_alongside_a_bare_one(): void
    {
        $session = $this->withProtocol('<p>A<B und <strong>fett</strong></p>');

        $text = $session->protocolText();

        $this->assertStringContainsString('A<B', $text);
        $this->assertStringContainsString('fett', $text);
        $this->assertStringNotContainsString('<strong>', $text);
    }

    #[Test]
    public function a_table_keeps_its_cells_apart(): void
    {
        $session = $this->withProtocol('<table><tr><td>Ton</td><td>Register</td></tr></table>');

        // Without `</td>` in the block list these ran together as "TonRegister".
        $this->assertStringNotContainsString('TonRegister', $session->protocolText());
    }

    // ── Nothing to read ─────────────────────────────────────────────────────

    #[Test]
    public function a_protocol_of_only_tags_is_no_protocol(): void
    {
        // The column holds something and the screen would hold nothing: a
        // template branching on `has_protocol` rendered an empty block under a
        // heading.
        $session = $this->withProtocol('<p></p><div>   </div>');

        $this->assertFalse($session->hasProtocol());
        $this->assertNull($session->protocolText());
        $this->assertSame([], $session->protocolBlocks());
    }

    // ── Structure without markup ────────────────────────────────────────────

    #[Test]
    public function the_write_up_keeps_its_headings_apart_from_its_paragraphs(): void
    {
        $session = $this->withProtocol(
            '<h3>Was wir gemacht haben</h3><p>Passaggio geübt.</p><h3>Bis zum nächsten Mal</h3><p>Zwei Minuten ng.</p>'
        );

        $blocks = $session->protocolBlocks();

        $this->assertSame(
            [
                ['type' => 'heading', 'text' => 'Was wir gemacht haben'],
                ['type' => 'text', 'text' => 'Passaggio geübt.'],
                ['type' => 'heading', 'text' => 'Bis zum nächsten Mal'],
                ['type' => 'text', 'text' => 'Zwei Minuten ng.'],
            ],
            $blocks,
        );

        // Still no markup in any of it — the elements are the screen's own.
        foreach ($blocks as $block) {
            $this->assertStringNotContainsString('<', $block['text']);
        }
    }

    #[Test]
    public function a_write_up_without_headings_is_one_block_of_text(): void
    {
        $session = $this->withProtocol('<p>Nur ein Absatz.</p>');

        $this->assertSame([['type' => 'text', 'text' => 'Nur ein Absatz.']], $session->protocolBlocks());
    }

    // ── The two names, and the exception ────────────────────────────────────

    #[Test]
    public function the_tag_escapes_the_text_and_hands_the_markup_over_untouched(): void
    {
        $this->withProtocol('<h3>Kopf</h3><p>Text mit <script>alert(1)</script> darin.</p>');

        $this->actAsClient();

        $escaped = $this->parse('{{ client_room }}{{ sessions }}{{ protocol }}{{ /sessions }}{{ /client_room }}');

        // The safe half: no tag survives, and what is left is escaped like
        // every other value in this shape.
        $this->assertStringNotContainsString('<script>', $escaped);
        $this->assertStringContainsString('Kopf', $escaped);

        $raw = $this->parse('{{ client_room }}{{ sessions }}{{ protocol_html }}{{ /sessions }}{{ /client_room }}');

        // The declared exception: exactly what arrived, because a site that
        // prints this has decided to trust the system that wrote it. Named in
        // the README so nobody meets it by accident.
        $this->assertStringContainsString('<h3>Kopf</h3>', $raw);
    }

    #[Test]
    public function the_members_json_speaks_the_same_two_names(): void
    {
        $this->withProtocol('<h3>Kopf</h3><p>Text.</p>');

        $response = $this->actingAs($this->frontendUser('maria@example.com'))
            ->getJson('/!/statamic-clientrooms/me');

        $response->assertOk();

        $session = $response->json('sessions.0');

        // Before, `protocol` meant plain text in the tag and raw HTML here —
        // a trap in both directions for a front end that reads the README once.
        $this->assertStringNotContainsString('<', $session['protocol']);
        $this->assertStringContainsString('Kopf', $session['protocol']);
        $this->assertStringContainsString('<h3>Kopf</h3>', $session['protocol_html']);
        $this->assertTrue($session['has_protocol']);
    }

    #[Test]
    public function the_coachs_note_is_in_neither_name(): void
    {
        $room = $this->room();

        ClientRooms::importSession($room, 'vf-0001', [
            'title' => 'Sitzung',
            'published_status' => ClientRoomSession::PUBLISHED_PUBLISHED,
            'protocol' => '<p>Für den Klienten.</p>',
            'notes' => 'Sie drückt beim hohen A.',
        ]);

        $this->actAsClient();

        $output = $this->parse(
            '{{ client_room }}{{ sessions }}{{ protocol }}|{{ protocol_html }}{{ /sessions }}{{ /client_room }}'
        );

        $this->assertStringContainsString('Für den Klienten.', $output);
        $this->assertStringNotContainsString('hohen A', $output);
    }
}
